apiVersion: v1
kind: Service
metadata:
  name:  odoo-db-svc
  namespace: icgroup
  labels:
    app: odoo
    env: prod 
spec:
  type: ClusterIP
  selector:
    app: odoo
    env: prod
  ports:
  - protocol:  TCP
    port:  5432
    targetPort: 5432