apiVersion: v1
kind: Service
metadata:
  name:  odoo-web-svc
  namespace: icgroup
  labels:
    app: odoo
    env: prod 
spec:
  type: NodePort
  selector:
    app: odoo
    env: prod
  ports:
  - protocol:  TCP
    port:  8069
    targetPort: 8069
    nodePort: 30008 