apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo 
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
      env: prod 
  template:
    metadata:
      labels:
        app: odoo
        env: prod
    spec:
      containers:
      - name: odoo
        image: odoo 
        env:
        - name: HOST
          value: postgres 
        - name: USER
          value: toto 
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo 
              key: PASSWORD 
        ports:
        - name: odoo
          containerPort: 8069 
        volumeMounts:
        - name: odoo-web-data
          mountPath: /var/lib/odoo
        - name: odoo-persistent-storage
          mountPath: /etc/odoo
        - name: extra-addons-persistent-storage
          mountPath: /mnt/extra-addons

      volumes:
        - name: odoo-web-data
          hostPath:
            path: /data/odoo-web-data/ 
        - name: odoo-persistent-storage
          hostPath:
            path: /data/config/
        - name: extra-addons-persistent-storage
          hostPath:
            path: /data/addons/