apiVersion: v1
kind: Service
metadata:
  name:  ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod 
spec:
  type: NodePort
  selector:
    app: ic-webapp
    env: prod
  ports:
  - protocol:  TCP
    port:  8080
    targetPort: 8080
    nodePort: 30080 