version: '3.1'
services:
  Odoo_web:
    platform: linux/amd64
    image: odoo:16.0
    depends_on:
      - BDD_Odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=BDD_Odoo
      - USER=odoo
      - PASSWORD=myodoo
    networks:
      - odoo-network 
  BDD_Odoo:
    platform: linux/amd64
    image: postgres:15 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network 
volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo-network: